# Generated by Django 2.0.2 on 2018-03-05 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infograph',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cid', models.PositiveIntegerField()),
                ('statusID', models.PositiveIntegerField()),
                ('sourceID', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Infograph',
                'verbose_name_plural': 'Infographs',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='InfographAssociations',
            fields=[
                ('iad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('iid', models.PositiveIntegerField()),
                ('tid', models.PositiveIntegerField()),
                ('mtgid', models.PositiveIntegerField()),
                ('eid', models.PositiveIntegerField()),
                ('gpid', models.PositiveIntegerField()),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('statusid', models.PositiveIntegerField()),
                ('inforgraph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Infograph')),
            ],
        ),
        migrations.CreateModel(
            name='InfographCategory',
            fields=[
                ('pid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'InfographCategory',
                'verbose_name_plural': 'InfographCategories',
            },
        ),
        migrations.CreateModel(
            name='ParentInfograph',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='pid')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ParentInfograph',
                'verbose_name_plural': 'ParentInfographs',
                'ordering': ['datecreated'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('tid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mtid', models.PositiveIntegerField()),
                ('topic_code', models.CharField(max_length=50)),
                ('topicdescription', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.AddField(
            model_name='infographassociations',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Topic'),
        ),
        migrations.AddField(
            model_name='infograph',
            name='infograph_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exampleapp.InfographCategory'),
        ),
        migrations.AddField(
            model_name='infograph',
            name='parentinfograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.ParentInfograph'),
        ),
    ]
